// community-templates/vue-ts-vite-tailwind/src/App.vue
<script setup lang="ts">
// Define reactive data
import { ref } from 'vue'
import TheWelcome from './components/TheWelcome.vue'

const message = ref('Hello Vue 3 + TypeScript + Tailwind!')
const count = ref(0)

// Define methods
const increment = () => {
  count.value++
}

const reset = () => {
  count.value = 0
}
</script>

<template>
  <div class="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100">
    <!-- Header -->
    <header class="bg-white shadow-sm">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between items-center py-6">
          <div class="flex items-center">
            <h1 class="text-2xl font-bold text-gray-900">🟢 Vue 3 Template</h1>
          </div>
          <nav class="hidden md:flex space-x-8">
            <a href="#features" class="text-gray-500 hover:text-gray-900">Features</a>
            <a href="#components" class="text-gray-500 hover:text-gray-900">Components</a>
            <a href="#docs" class="text-gray-500 hover:text-gray-900">Docs</a>
          </nav>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <main class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <!-- Hero Section -->
      <div class="text-center mb-16">
        <h2 class="text-4xl font-extrabold text-gray-900 sm:text-5xl mb-4">
          {{ message }}
        </h2>
        <p class="text-xl text-gray-600 mb-8 max-w-2xl mx-auto">
          A minimal, production-ready Vue 3 starter template with TypeScript, Vite, and Tailwind CSS.
          Start building amazing applications today!
        </p>

        <!-- Counter Demo -->
        <div class="bg-white rounded-lg shadow-md p-8 mb-8 max-w-md mx-auto">
          <h3 class="text-lg font-semibold text-gray-900 mb-4">Interactive Counter</h3>
          <div class="text-6xl font-bold text-indigo-600 mb-4">{{ count }}</div>
          <div class="flex space-x-4 justify-center">
            <button
              @click="increment"
              class="bg-indigo-600 hover:bg-indigo-700 text-white font-medium py-2 px-4 rounded-lg transition duration-200"
            >
              Increment
            </button>
            <button
              @click="reset"
              class="bg-gray-500 hover:bg-gray-600 text-white font-medium py-2 px-4 rounded-lg transition duration-200"
            >
              Reset
            </button>
          </div>
        </div>
      </div>

      <!-- Features Grid -->
      <div id="features" class="mb-16">
        <h3 class="text-3xl font-bold text-gray-900 text-center mb-8">✨ Key Features</h3>
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          <!-- Vue 3 -->
          <div class="bg-white rounded-lg shadow-md p-6">
            <div class="w-12 h-12 bg-green-100 rounded-lg flex items-center justify-center mb-4">
              <span class="text-2xl">🟢</span>
            </div>
            <h4 class="text-xl font-semibold text-gray-900 mb-2">Vue 3</h4>
            <p class="text-gray-600">
              Latest Vue 3 with Composition API, providing better performance and developer experience.
            </p>
          </div>

          <!-- TypeScript -->
          <div class="bg-white rounded-lg shadow-md p-6">
            <div class="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center mb-4">
              <span class="text-2xl">🔷</span>
            </div>
            <h4 class="text-xl font-semibold text-gray-900 mb-2">TypeScript</h4>
            <p class="text-gray-600">
              Full TypeScript support with strict type checking and excellent IDE support.
            </p>
          </div>

          <!-- Vite -->
          <div class="bg-white rounded-lg shadow-md p-6">
            <div class="w-12 h-12 bg-yellow-100 rounded-lg flex items-center justify-center mb-4">
              <span class="text-2xl">⚡</span>
            </div>
            <h4 class="text-xl font-semibold text-gray-900 mb-2">Vite</h4>
            <p class="text-gray-600">
              Lightning-fast build tool with instant hot module replacement during development.
            </p>
          </div>

          <!-- Tailwind CSS -->
          <div class="bg-white rounded-lg shadow-md p-6">
            <div class="w-12 h-12 bg-teal-100 rounded-lg flex items-center justify-center mb-4">
              <span class="text-2xl">🎨</span>
            </div>
            <h4 class="text-xl font-semibold text-gray-900 mb-2">Tailwind CSS</h4>
            <p class="text-gray-600">
              Utility-first CSS framework for rapid UI development with responsive design.
            </p>
          </div>

          <!-- ESLint -->
          <div class="bg-white rounded-lg shadow-md p-6">
            <div class="w-12 h-12 bg-purple-100 rounded-lg flex items-center justify-center mb-4">
              <span class="text-2xl">🔍</span>
            </div>
            <h4 class="text-xl font-semibold text-gray-900 mb-2">ESLint</h4>
            <p class="text-gray-600">
              Code linting and formatting with Prettier integration for consistent code quality.
            </p>
          </div>

          <!-- Production Ready -->
          <div class="bg-white rounded-lg shadow-md p-6">
            <div class="w-12 h-12 bg-orange-100 rounded-lg flex items-center justify-center mb-4">
              <span class="text-2xl">🚀</span>
            </div>
            <h4 class="text-xl font-semibold text-gray-900 mb-2">Production Ready</h4>
            <p class="text-gray-600">
              Optimized build configuration and deployment ready setup for production use.
            </p>
          </div>
        </div>
      </div>

      <!-- Welcome Component -->
      <div id="components" class="mb-16">
        <h3 class="text-3xl font-bold text-gray-900 text-center mb-8">🧩 Component Demo</h3>
        <TheWelcome />
      </div>

      <!-- Getting Started -->
      <div id="docs" class="bg-white rounded-lg shadow-md p-8">
        <h3 class="text-3xl font-bold text-gray-900 text-center mb-8">🚀 Getting Started</h3>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div>
            <h4 class="text-xl font-semibold text-gray-900 mb-4">Installation</h4>
            <div class="bg-gray-50 rounded-lg p-4 font-mono text-sm">
              <div class="mb-2"># Copy this template</div>
              <div class="mb-2">cp -r vue-ts-vite-tailwind my-app</div>
              <div class="mb-2">cd my-app</div>
              <div class="mb-2"># Install dependencies</div>
              <div>npm install</div>
            </div>
          </div>
          <div>
            <h4 class="text-xl font-semibold text-gray-900 mb-4">Development</h4>
            <div class="bg-gray-50 rounded-lg p-4 font-mono text-sm">
              <div class="mb-2"># Start development server</div>
              <div class="mb-2">npm run dev</div>
              <div class="mb-2"># Build for production</div>
              <div class="mb-2">npm run build</div>
              <div class="mb-2"># Preview production build</div>
              <div>npm run preview</div>
            </div>
          </div>
        </div>
      </div>
    </main>

    <!-- Footer -->
    <footer class="bg-gray-50 border-t">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div class="text-center text-gray-600">
          <p>Built with Vue 3, TypeScript, Vite, and Tailwind CSS</p>
          <p class="mt-2">Part of the Codiner Community Templates Collection</p>
        </div>
      </div>
    </footer>
  </div>
</template>

<style scoped>
/* Component-specific styles can go here */
</style>

// community-templates/electron-svelte-ts/src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import Counter from './components/Counter.svelte';
  import FileManager from './components/FileManager.svelte';
  import SystemInfo from './components/SystemInfo.svelte';

  let activeTab = 'home';

  // Handle file operations from menu
  onMount(() => {
    if (window.electronAPI) {
      window.electronAPI.onFileOpened((filePath) => {
        console.log('File opened:', filePath);
        activeTab = 'files';
        // Trigger file loading logic here
      });

      window.electronAPI.onFileSaveRequested((filePath) => {
        console.log('File save requested:', filePath);
        // Trigger file saving logic here
      });
    }

    return () => {
      if (window.electronAPI) {
        window.electronAPI.removeAllListeners('file-opened');
        window.electronAPI.removeAllListeners('file-save-requested');
      }
    };
  });
</script>

<main class="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 dark:from-slate-950 dark:to-slate-900">
  <!-- Navigation -->
  <nav class="border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex justify-between h-16">
        <div class="flex items-center">
          <h1 class="text-xl font-bold text-gray-900 dark:text-white">
            ⚡ Electron + Svelte Template
          </h1>
        </div>
        <div class="flex items-center space-x-8">
          <button
            on:click={() => activeTab = 'home'}
            class="px-3 py-2 rounded-md text-sm font-medium transition-colors"
            class:text-blue-600={activeTab === 'home'}
            class:text-gray-500={activeTab !== 'home'}
            class:hover:text-gray-900={activeTab !== 'home'}
          >
            Home
          </button>
          <button
            on:click={() => activeTab = 'files'}
            class="px-3 py-2 rounded-md text-sm font-medium transition-colors"
            class:text-blue-600={activeTab === 'files'}
            class:text-gray-500={activeTab !== 'files'}
            class:hover:text-gray-900={activeTab !== 'files'}
          >
            Files
          </button>
          <button
            on:click={() => activeTab = 'system'}
            class="px-3 py-2 rounded-md text-sm font-medium transition-colors"
            class:text-blue-600={activeTab === 'system'}
            class:text-gray-500={activeTab !== 'system'}
            class:hover:text-gray-900={activeTab !== 'system'}
          >
            System
          </button>
        </div>
      </div>
    </div>
  </nav>

  <!-- Content -->
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
    {#if activeTab === 'home'}
      <!-- Home Tab -->
      <div class="text-center mb-12">
        <h2 class="text-4xl font-bold tracking-tight mb-4">
          Welcome to Electron + Svelte
        </h2>
        <p class="text-xl text-muted-foreground max-w-3xl mx-auto mb-8">
          Build cross-platform desktop applications with Electron and Svelte.
          Experience the power of native desktop development with modern web technologies.
        </p>

        <div class="flex justify-center gap-4 mb-8">
          <span class="px-3 py-1 bg-purple-100 dark:bg-purple-900 text-purple-800 dark:text-purple-200 rounded-full text-sm font-medium">Electron</span>
          <span class="px-3 py-1 bg-orange-100 dark:bg-orange-900 text-orange-800 dark:text-orange-200 rounded-full text-sm font-medium">Svelte 5</span>
          <span class="px-3 py-1 bg-blue-100 dark:bg-blue-900 text-blue-800 dark:text-blue-200 rounded-full text-sm font-medium">TypeScript</span>
          <span class="px-3 py-1 bg-teal-100 dark:bg-teal-900 text-teal-800 dark:text-teal-200 rounded-full text-sm font-medium">Tailwind</span>
        </div>
      </div>

      <!-- Features Grid -->
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mb-12">
        <div class="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6">
          <div class="w-12 h-12 bg-purple-100 dark:bg-purple-900 rounded-lg flex items-center justify-center mb-4">
            <span class="text-2xl">⚡</span>
          </div>
          <h3 class="text-xl font-semibold mb-2">Native Performance</h3>
          <p class="text-muted-foreground">
            Direct OS integration with Node.js and Chromium runtime
          </p>
        </div>

        <div class="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6">
          <div class="w-12 h-12 bg-orange-100 dark:bg-orange-900 rounded-lg flex items-center justify-center mb-4">
            <span class="text-2xl">🧡</span>
          </div>
          <h3 class="text-xl font-semibold mb-2">Svelte 5</h3>
          <p class="text-muted-foreground">
            Latest Svelte with runes, signals, and enhanced reactivity
          </p>
        </div>

        <div class="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6">
          <div class="w-12 h-12 bg-blue-100 dark:bg-blue-900 rounded-lg flex items-center justify-center mb-4">
            <span class="text-2xl">🔷</span>
          </div>
          <h3 class="text-xl font-semibold mb-2">TypeScript</h3>
          <p class="text-muted-foreground">
            Full TypeScript support with type-safe IPC communication
          </p>
        </div>

        <div class="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6">
          <div class="w-12 h-12 bg-green-100 dark:bg-green-900 rounded-lg flex items-center justify-center mb-4">
            <span class="text-2xl">📁</span>
          </div>
          <h3 class="text-xl font-semibold mb-2">File System</h3>
          <p class="text-muted-foreground">
            Native file system access with secure IPC communication
          </p>
        </div>

        <div class="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6">
          <div class="w-12 h-12 bg-teal-100 dark:bg-teal-900 rounded-lg flex items-center justify-center mb-4">
            <span class="text-2xl">🎨</span>
          </div>
          <h3 class="text-xl font-semibold mb-2">Tailwind CSS</h3>
          <p class="text-muted-foreground">
            Utility-first CSS framework for rapid UI development
          </p>
        </div>

        <div class="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6">
          <div class="w-12 h-12 bg-indigo-100 dark:bg-indigo-900 rounded-lg flex items-center justify-center mb-4">
            <span class="text-2xl">📦</span>
          </div>
          <h3 class="text-xl font-semibold mb-2">Cross-Platform</h3>
          <p class="text-muted-foreground">
            Build for Windows, macOS, and Linux from single codebase
          </p>
        </div>
      </div>

      <!-- Counter Demo -->
      <div class="max-w-md mx-auto">
        <Counter />
      </div>

    {:else if activeTab === 'files'}
      <FileManager />
    {:else if activeTab === 'system'}
      <SystemInfo />
    {/if}
  </div>

  <!-- Footer -->
  <footer class="border-t bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 mt-12">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <div class="text-center text-gray-600 dark:text-gray-400">
        <p>Built with Electron, Svelte 5, TypeScript, and Tailwind CSS</p>
        <p class="mt-2">Cross-platform desktop applications made easy</p>
      </div>
    </div>
  </footer>
</main>

<style>
  :global(html) {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
  }

  :global(body) {
    margin: 0;
    padding: 0;
    min-height: 100vh;
  }
</style>
