// community-templates/angular-codiner/src/app/about/about.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-about',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="px-4 py-6 sm:px-0">
      <!-- Header -->
      <div class="text-center mb-12">
        <h1 class="text-3xl font-bold text-gray-900 sm:text-4xl mb-4">
          About This Angular Template
        </h1>
        <p class="text-xl text-gray-600 max-w-2xl mx-auto">
          Learn more about this Angular template designed specifically for development in Codiner.
        </p>
      </div>

      <!-- Content Sections -->
      <div class="space-y-8">
        <!-- What is Angular -->
        <div class="bg-white rounded-lg shadow-md p-8">
          <h2 class="text-2xl font-bold text-gray-900 mb-4">🅰️ What is Angular?</h2>
          <p class="text-gray-600 mb-4">
            Angular is a platform and framework for building single-page client applications using HTML and TypeScript.
            It implements core and optional functionality as a set of TypeScript libraries that you import into your applications.
          </p>
          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <h3 class="text-lg font-semibold text-gray-900 mb-2">Key Features</h3>
              <ul class="text-gray-600 space-y-1">
                <li>• Declarative UI with HTML templates</li>
                <li>• Component-based architecture</li>
                <li>• Dependency injection</li>
                <li>• Reactive programming with RxJS</li>
                <li>• TypeScript-first development</li>
              </ul>
            </div>
            <div>
              <h3 class="text-lg font-semibold text-gray-900 mb-2">Modern Concepts</h3>
              <ul class="text-gray-600 space-y-1">
                <li>• Standalone components</li>
                <li>• Signals for reactivity</li>
                <li>• Control flow syntax</li>
                <li>• Functional guards</li>
                <li>• Improved developer experience</li>
              </ul>
            </div>
          </div>
        </div>

        <!-- Project Structure -->
        <div class="bg-white rounded-lg shadow-md p-8">
          <h2 class="text-2xl font-bold text-gray-900 mb-4">📁 Project Structure</h2>
          <div class="bg-gray-50 rounded-lg p-4 font-mono text-sm">
            <div class="mb-2">angular-codiner/</div>
            <div class="ml-4 mb-1">├── src/</div>
            <div class="ml-8 mb-1">│   ├── app/</div>
            <div class="ml-12 mb-1">│   │   ├── home/</div>
            <div class="ml-12 mb-1">│   │   ├── about/</div>
            <div class="ml-12 mb-1">│   │   ├── app.component.ts</div>
            <div class="ml-12 mb-1">│   │   ├── app.config.ts</div>
            <div class="ml-12 mb-1">│   │   └── app.routes.ts</div>
            <div class="ml-8 mb-1">│   ├── assets/</div>
            <div class="ml-8 mb-1">│   ├── index.html</div>
            <div class="ml-8 mb-1">│   ├── main.ts</div>
            <div class="ml-8 mb-1">│   └── styles.css</div>
            <div class="ml-4 mb-1">├── angular.json</div>
            <div class="ml-4 mb-1">├── package.json</div>
            <div class="ml-4 mb-1">└── tsconfig.json</div>
          </div>
        </div>

        <!-- Technologies Used -->
        <div class="bg-white rounded-lg shadow-md p-8">
          <h2 class="text-2xl font-bold text-gray-900 mb-4">🛠️ Technologies Used</h2>
          <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            <div class="border border-gray-200 rounded-lg p-4">
              <h3 class="font-semibold text-gray-900 mb-2">Angular 17</h3>
              <p class="text-sm text-gray-600">Latest Angular framework with modern features</p>
            </div>
            <div class="border border-gray-200 rounded-lg p-4">
              <h3 class="font-semibold text-gray-900 mb-2">TypeScript 5.2</h3>
              <p class="text-sm text-gray-600">Type-safe JavaScript with latest features</p>
            </div>
            <div class="border border-gray-200 rounded-lg p-4">
              <h3 class="font-semibold text-gray-900 mb-2">RxJS</h3>
              <p class="text-sm text-gray-600">Reactive programming library</p>
            </div>
            <div class="border border-gray-200 rounded-lg p-4">
              <h3 class="font-semibold text-gray-900 mb-2">ESLint</h3>
              <p class="text-sm text-gray-600">Code linting and formatting</p>
            </div>
            <div class="border border-gray-200 rounded-lg p-4">
              <h3 class="font-semibold text-gray-900 mb-2">Jasmine & Karma</h3>
              <p class="text-sm text-gray-600">Testing framework and test runner</p>
            </div>
            <div class="border border-gray-200 rounded-lg p-4">
              <h3 class="font-semibold text-gray-900 mb-2">Tailwind CSS</h3>
              <p class="text-sm text-gray-600">Utility-first CSS framework</p>
            </div>
          </div>
        </div>

        <!-- Development Tips -->
        <div class="bg-white rounded-lg shadow-md p-8">
          <h2 class="text-2xl font-bold text-gray-900 mb-4">💡 Development Tips</h2>
          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <h3 class="text-lg font-semibold text-gray-900 mb-3">Standalone Components</h3>
              <p class="text-gray-600 mb-3">
                Use standalone components for better tree-shaking and simpler architecture.
              </p>
              <div class="bg-gray-50 rounded p-3 font-mono text-sm">
                @Component({{ '{' }}<br>
                &nbsp;&nbsp;standalone: true,<br>
                &nbsp;&nbsp;imports: [CommonModule],<br>
                &nbsp;&nbsp;// ...<br>
                })
              </div>
            </div>
            <div>
              <h3 class="text-lg font-semibold text-gray-900 mb-3">Signals</h3>
              <p class="text-gray-600 mb-3">
                Use signals for reactive state management and better performance.
              </p>
              <div class="bg-gray-50 rounded p-3 font-mono text-sm">
                const count = signal(0);<br>
                count.update(val => val + 1);
              </div>
            </div>
          </div>
        </div>

        <!-- Resources -->
        <div class="bg-white rounded-lg shadow-md p-8">
          <h2 class="text-2xl font-bold text-gray-900 mb-4">📚 Resources</h2>
          <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <a
              href="https://angular.io/docs"
              target="_blank"
              rel="noopener noreferrer"
              class="flex items-center p-4 border border-gray-200 rounded-lg hover:bg-gray-50 transition duration-200"
            >
              <span class="text-2xl mr-3">📖</span>
              <div>
                <div class="font-semibold text-gray-900">Angular Documentation</div>
                <div class="text-sm text-gray-600">Official Angular docs and guides</div>
              </div>
            </a>
            <a
              href="https://angular.io/guide/standalone-components"
              target="_blank"
              rel="noopener noreferrer"
              class="flex items-center p-4 border border-gray-200 rounded-lg hover:bg-gray-50 transition duration-200"
            >
              <span class="text-2xl mr-3">🧩</span>
              <div>
                <div class="font-semibold text-gray-900">Standalone Components</div>
                <div class="text-sm text-gray-600">Guide to modern component architecture</div>
              </div>
            </a>
            <a
              href="https://angular.io/guide/signals"
              target="_blank"
              rel="noopener noreferrer"
              class="flex items-center p-4 border border-gray-200 rounded-lg hover:bg-gray-50 transition duration-200"
            >
              <span class="text-2xl mr-3">⚡</span>
              <div>
                <div class="font-semibold text-gray-900">Signals</div>
                <div class="text-sm text-gray-600">Reactive signals documentation</div>
              </div>
            </a>
            <a
              href="https://www.typescriptlang.org/docs/"
              target="_blank"
              rel="noopener noreferrer"
              class="flex items-center p-4 border border-gray-200 rounded-lg hover:bg-gray-50 transition duration-200"
            >
              <span class="text-2xl mr-3">🔷</span>
              <div>
                <div class="font-semibold text-gray-900">TypeScript Handbook</div>
                <div class="text-sm text-gray-600">Comprehensive TypeScript guide</div>
              </div>
            </a>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: []
})
export class AboutComponent {}

// community-templates/react-router-7/app/routes/about.tsx
import type { Route } from "./+types/about";
import { Layout } from "~/components/layout";

export function meta({}: Route.MetaArgs) {
  return [
    { title: "About - React Router 7 Template" },
    { name: "description", content: "Learn about React Router 7 and file-based routing" },
  ];
}

export default function About() {
  return (
    <Layout>
      <div className="px-4 py-6 sm:px-0">
        {/* Header */}
        <div className="text-center mb-12">
          <h1 className="text-3xl font-bold text-gray-900 sm:text-4xl mb-4">
            About React Router 7
          </h1>
          <p className="text-xl text-gray-600 max-w-2xl mx-auto">
            Discover the power of file-based routing and modern React development
            with React Router 7.
          </p>
        </div>

        {/* Content Sections */}
        <div className="space-y-8">
          {/* What is React Router 7 */}
          <div className="bg-white rounded-lg shadow-md p-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">🚀 What is React Router 7?</h2>
            <p className="text-gray-600 mb-4">
              React Router 7 is the latest evolution of React Router, bringing powerful new features
              including file-based routing, automatic route generation, and enhanced developer experience.
              It represents a significant leap forward in how we think about routing in React applications.
            </p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <h3 className="text-lg font-semibold text-gray-900 mb-2">Key Innovations</h3>
                <ul className="text-gray-600 space-y-1">
                  <li>• File-based routing system</li>
                  <li>• Automatic route generation</li>
                  <li>• Enhanced TypeScript support</li>
                  <li>• Built-in data loading</li>
                  <li>• Nested route layouts</li>
                  <li>• Improved developer tools</li>
                </ul>
              </div>
              <div>
                <h3 className="text-lg font-semibold text-gray-900 mb-2">Benefits</h3>
                <ul className="text-gray-600 space-y-1">
                  <li>• Zero configuration routing</li>
                  <li>• Type-safe route parameters</li>
                  <li>• Better performance</li>
                  <li>• Simplified architecture</li>
                  <li>• Enhanced DX</li>
                  <li>• Future-proof design</li>
                </ul>
              </div>
            </div>
          </div>

          {/* File-Based Routing */}
          <div className="bg-white rounded-lg shadow-md p-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">📁 File-Based Routing</h2>
            <p className="text-gray-600 mb-6">
              React Router 7 introduces a revolutionary file-based routing system where your file
              structure directly determines your application's routes. This approach eliminates
              the need for manual route configuration and provides a more intuitive development experience.
            </p>

            <div className="bg-gray-50 rounded-lg p-6 font-mono text-sm">
              <div className="mb-4 text-gray-700 font-semibold">Example Route Structure:</div>
              <div className="space-y-1">
                <div>app/</div>
                <div>&nbsp;&nbsp;routes/</div>
                <div>&nbsp;&nbsp;&nbsp;&nbsp;_index.tsx &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; → /</div>
                <div>&nbsp;&nbsp;&nbsp;&nbsp;about.tsx &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; → /about</div>
                <div>&nbsp;&nbsp;&nbsp;&nbsp;dashboard.tsx &nbsp;&nbsp;&nbsp;&nbsp; → /dashboard</div>
                <div>&nbsp;&nbsp;&nbsp;&nbsp;blog/</div>
                <div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_index.tsx &nbsp;&nbsp;&nbsp;&nbsp; → /blog</div>
                <div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$postId.tsx &nbsp;&nbsp;&nbsp; → /blog/:postId</div>
                <div>&nbsp;&nbsp;&nbsp;&nbsp;users/</div>
                <div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;profile.tsx &nbsp;&nbsp;&nbsp; → /users/profile</div>
              </div>
            </div>

            <div className="mt-6 grid grid-cols-1 md:grid-cols-3 gap-4">
              <div className="text-center">
                <div className="text-2xl mb-2">📄</div>
                <div className="font-semibold text-gray-900">Static Routes</div>
                <div className="text-sm text-gray-600">Direct file to route mapping</div>
              </div>
              <div className="text-center">
                <div className="text-2xl mb-2">🌀</div>
                <div className="font-semibold text-gray-900">Dynamic Routes</div>
                <div className="text-sm text-gray-600">$param.tsx for parameters</div>
              </div>
              <div className="text-center">
                <div className="text-2xl mb-2">📁</div>
                <div className="font-semibold text-gray-900">Nested Routes</div>
                <div className="text-sm text-gray-600">Folder-based organization</div>
              </div>
            </div>
          </div>

          {/* Features Comparison */}
          <div className="bg-white rounded-lg shadow-md p-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">⚡ Performance & DX</h2>
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b">
                    <th className="text-left py-2 font-semibold text-gray-900">Feature</th>
                    <th className="text-left py-2 font-semibold text-gray-900">React Router 6</th>
                    <th className="text-left py-2 font-semibold text-gray-900">React Router 7</th>
                  </tr>
                </thead>
                <tbody className="text-gray-600">
                  <tr className="border-b">
                    <td className="py-3">Route Configuration</td>
                    <td>Manual route objects</td>
                    <td>Automatic from file system</td>
                  </tr>
                  <tr className="border-b">
                    <td className="py-3">TypeScript Support</td>
                    <td>Basic types</td>
                    <td>Full type generation</td>
                  </tr>
                  <tr className="border-b">
                    <td className="py-3">Data Loading</td>
                    <td>useEffect patterns</td>
                    <td>Built-in loaders</td>
                  </tr>
                  <tr className="border-b">
                    <td className="py-3">Code Splitting</td>
                    <td>Manual lazy loading</td>
                    <td>Automatic route-based</td>
                  </tr>
                  <tr>
                    <td className="py-3">Developer Experience</td>
                    <td>Good</td>
                    <td>Exceptional</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          {/* Migration Guide */}
          <div className="bg-white rounded-lg shadow-md p-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">🔄 Migration Guide</h2>
            <div className="space-y-4">
              <div className="border-l-4 border-blue-500 pl-4">
                <h3 className="font-semibold text-gray-900">From React Router 6</h3>
                <p className="text-gray-600 mt-1">
                  Migrating from React Router 6 is straightforward. The main change is moving
                  from manual route configuration to file-based routing.
                </p>
              </div>

              <div className="bg-gray-50 rounded-lg p-4">
                <h4 className="font-semibold text-gray-900 mb-2">Key Migration Steps:</h4>
                <ol className="list-decimal list-inside text-gray-600 space-y-1">
                  <li>Install React Router 7 dependencies</li>
                  <li>Move route components to <code className="bg-gray-200 px-1 rounded">app/routes/</code> folder</li>
                  <li>Rename files to match URL structure</li>
                  <li>Replace route configuration with file structure</li>
                  <li>Update imports to use new route types</li>
                </ol>
              </div>
            </div>
          </div>

          {/* Resources */}
          <div className="bg-white rounded-lg shadow-md p-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">📚 Resources & Documentation</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <a
                href="https://reactrouter.com/"
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center p-4 border border-gray-200 rounded-lg hover:bg-gray-50 transition duration-200"
              >
                <span className="text-2xl mr-3">📖</span>
                <div>
                  <div className="font-semibold text-gray-900">Official Documentation</div>
                  <div className="text-sm text-gray-600">Complete React Router 7 docs</div>
                </div>
              </a>
              <a
                href="https://github.com/remix-run/react-router"
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center p-4 border border-gray-200 rounded-lg hover:bg-gray-50 transition duration-200"
              >
                <span className="text-2xl mr-3">💻</span>
                <div>
                  <div className="font-semibold text-gray-900">GitHub Repository</div>
                  <div className="text-sm text-gray-600">Source code and issues</div>
                </div>
              </a>
              <a
                href="https://reactrouter.com/start/tutorial"
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center p-4 border border-gray-200 rounded-lg hover:bg-gray-50 transition duration-200"
              >
                <span className="text-2xl mr-3">🎓</span>
                <div>
                  <div className="font-semibold text-gray-900">Tutorial</div>
                  <div className="text-sm text-gray-600">Step-by-step learning guide</div>
                </div>
              </a>
              <a
                href="https://discord.gg/Remix"
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center p-4 border border-gray-200 rounded-lg hover:bg-gray-50 transition duration-200"
              >
                <span className="text-2xl mr-3">💬</span>
                <div>
                  <div className="font-semibold text-gray-900">Discord Community</div>
                  <div className="text-sm text-gray-600">Get help and share knowledge</div>
                </div>
              </a>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
}
