// community-templates/vue-ts-vite-tailwind/src/App.vue
<script setup lang="ts">
// Define reactive data
import { ref } from 'vue'
import TheWelcome from './components/TheWelcome.vue'

const message = ref('Hello Vue 3 + TypeScript + Tailwind!')
const count = ref(0)

// Define methods
const increment = () => {
  count.value++
}

const reset = () => {
  count.value = 0
}
</script>

<template>
  <div class="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100">
    <!-- Header -->
    <header class="bg-white shadow-sm">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between items-center py-6">
          <div class="flex items-center">
            <h1 class="text-2xl font-bold text-gray-900">🟢 Vue 3 Template</h1>
          </div>
          <nav class="hidden md:flex space-x-8">
            <a href="#features" class="text-gray-500 hover:text-gray-900">Features</a>
            <a href="#components" class="text-gray-500 hover:text-gray-900">Components</a>
            <a href="#docs" class="text-gray-500 hover:text-gray-900">Docs</a>
          </nav>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <main class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <!-- Hero Section -->
      <div class="text-center mb-16">
        <h2 class="text-4xl font-extrabold text-gray-900 sm:text-5xl mb-4">
          {{ message }}
        </h2>
        <p class="text-xl text-gray-600 mb-8 max-w-2xl mx-auto">
          A minimal, production-ready Vue 3 starter template with TypeScript, Vite, and Tailwind CSS.
          Start building amazing applications today!
        </p>

        <!-- Counter Demo -->
        <div class="bg-white rounded-lg shadow-md p-8 mb-8 max-w-md mx-auto">
          <h3 class="text-lg font-semibold text-gray-900 mb-4">Interactive Counter</h3>
          <div class="text-6xl font-bold text-indigo-600 mb-4">{{ count }}</div>
          <div class="flex space-x-4 justify-center">
            <button
              @click="increment"
              class="bg-indigo-600 hover:bg-indigo-700 text-white font-medium py-2 px-4 rounded-lg transition duration-200"
            >
              Increment
            </button>
            <button
              @click="reset"
              class="bg-gray-500 hover:bg-gray-600 text-white font-medium py-2 px-4 rounded-lg transition duration-200"
            >
              Reset
            </button>
          </div>
        </div>
      </div>

      <!-- Features Grid -->
      <div id="features" class="mb-16">
        <h3 class="text-3xl font-bold text-gray-900 text-center mb-8">✨ Key Features</h3>
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          <!-- Vue 3 -->
          <div class="bg-white rounded-lg shadow-md p-6">
            <div class="w-12 h-12 bg-green-100 rounded-lg flex items-center justify-center mb-4">
              <span class="text-2xl">🟢</span>
            </div>
            <h4 class="text-xl font-semibold text-gray-900 mb-2">Vue 3</h4>
            <p class="text-gray-600">
              Latest Vue 3 with Composition API, providing better performance and developer experience.
            </p>
          </div>

          <!-- TypeScript -->
          <div class="bg-white rounded-lg shadow-md p-6">
            <div class="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center mb-4">
              <span class="text-2xl">🔷</span>
            </div>
            <h4 class="text-xl font-semibold text-gray-900 mb-2">TypeScript</h4>
            <p class="text-gray-600">
              Full TypeScript support with strict type checking and excellent IDE support.
            </p>
          </div>

          <!-- Vite -->
          <div class="bg-white rounded-lg shadow-md p-6">
            <div class="w-12 h-12 bg-yellow-100 rounded-lg flex items-center justify-center mb-4">
              <span class="text-2xl">⚡</span>
            </div>
            <h4 class="text-xl font-semibold text-gray-900 mb-2">Vite</h4>
            <p class="text-gray-600">
              Lightning-fast build tool with instant hot module replacement during development.
            </p>
          </div>

          <!-- Tailwind CSS -->
          <div class="bg-white rounded-lg shadow-md p-6">
            <div class="w-12 h-12 bg-teal-100 rounded-lg flex items-center justify-center mb-4">
              <span class="text-2xl">🎨</span>
            </div>
            <h4 class="text-xl font-semibold text-gray-900 mb-2">Tailwind CSS</h4>
            <p class="text-gray-600">
              Utility-first CSS framework for rapid UI development with responsive design.
            </p>
          </div>

          <!-- ESLint -->
          <div class="bg-white rounded-lg shadow-md p-6">
            <div class="w-12 h-12 bg-purple-100 rounded-lg flex items-center justify-center mb-4">
              <span class="text-2xl">🔍</span>
            </div>
            <h4 class="text-xl font-semibold text-gray-900 mb-2">ESLint</h4>
            <p class="text-gray-600">
              Code linting and formatting with Prettier integration for consistent code quality.
            </p>
          </div>

          <!-- Production Ready -->
          <div class="bg-white rounded-lg shadow-md p-6">
            <div class="w-12 h-12 bg-orange-100 rounded-lg flex items-center justify-center mb-4">
              <span class="text-2xl">🚀</span>
            </div>
            <h4 class="text-xl font-semibold text-gray-900 mb-2">Production Ready</h4>
            <p class="text-gray-600">
              Optimized build configuration and deployment ready setup for production use.
            </p>
          </div>
        </div>
      </div>

      <!-- Welcome Component -->
      <div id="components" class="mb-16">
        <h3 class="text-3xl font-bold text-gray-900 text-center mb-8">🧩 Component Demo</h3>
        <TheWelcome />
      </div>

      <!-- Getting Started -->
      <div id="docs" class="bg-white rounded-lg shadow-md p-8">
        <h3 class="text-3xl font-bold text-gray-900 text-center mb-8">🚀 Getting Started</h3>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div>
            <h4 class="text-xl font-semibold text-gray-900 mb-4">Installation</h4>
            <div class="bg-gray-50 rounded-lg p-4 font-mono text-sm">
              <div class="mb-2"># Copy this template</div>
              <div class="mb-2">cp -r vue-ts-vite-tailwind my-app</div>
              <div class="mb-2">cd my-app</div>
              <div class="mb-2"># Install dependencies</div>
              <div>npm install</div>
            </div>
          </div>
          <div>
            <h4 class="text-xl font-semibold text-gray-900 mb-4">Development</h4>
            <div class="bg-gray-50 rounded-lg p-4 font-mono text-sm">
              <div class="mb-2"># Start development server</div>
              <div class="mb-2">npm run dev</div>
              <div class="mb-2"># Build for production</div>
              <div class="mb-2">npm run build</div>
              <div class="mb-2"># Preview production build</div>
              <div>npm run preview</div>
            </div>
          </div>
        </div>
      </div>
    </main>

    <!-- Footer -->
    <footer class="bg-gray-50 border-t">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div class="text-center text-gray-600">
          <p>Built with Vue 3, TypeScript, Vite, and Tailwind CSS</p>
          <p class="mt-2">Part of the Codiner Community Templates Collection</p>
        </div>
      </div>
    </footer>
  </div>
</template>

<style scoped>
/* Component-specific styles can go here */
</style>

// community-templates/bun-react-ts/src/App.tsx
import { useState, useEffect } from 'react';
import { Button } from './components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from './components/ui/card';
import { Badge } from './components/ui/badge';
import { Separator } from './components/ui/separator';
import { Counter } from './components/Counter';
import { ApiDemo } from './components/ApiDemo';
import { FileDemo } from './components/FileDemo';

function App() {
  const [systemInfo, setSystemInfo] = useState<any>(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    // Simulate loading system info (Bun-specific features would go here)
    const loadSystemInfo = async () => {
      // Bun has built-in APIs for system information
      const info = {
        runtime: 'Bun',
        version: '1.x.x', // Would use Bun.version in real Bun app
        platform: navigator.platform,
        userAgent: navigator.userAgent,
        timestamp: new Date().toISOString(),
      };
      setSystemInfo(info);
      setIsLoading(false);
    };

    loadSystemInfo();
  }, []);

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 dark:from-slate-950 dark:to-slate-900">
      {/* Header */}
      <header className="border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between h-16">
            <div className="flex items-center">
              <h1 className="text-xl font-bold text-gray-900 dark:text-white">
                ⚡ Bun + React + TypeScript
              </h1>
            </div>
            <div className="flex items-center space-x-8">
              <Badge variant="secondary">Bun Runtime</Badge>
              <Badge variant="outline">React 18</Badge>
              <Badge variant="outline">TypeScript</Badge>
            </div>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Hero Section */}
        <div className="text-center mb-12">
          <h1 className="text-4xl font-bold tracking-tight mb-4">
            Welcome to Bun
          </h1>
          <p className="text-xl text-muted-foreground max-w-3xl mx-auto mb-8">
            Experience lightning-fast development with Bun, a modern JavaScript runtime.
            Built-in bundling, TypeScript support, and native performance with React.
          </p>

          <div className="flex justify-center gap-4 mb-8">
            <Badge variant="secondary">⚡ Fast Startup</Badge>
            <Badge variant="outline">📦 Built-in Bundler</Badge>
            <Badge variant="outline">🔷 Native TypeScript</Badge>
            <Badge variant="outline">🎯 Drop-in Node.js</Badge>
          </div>
        </div>

        {/* Features Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mb-12">
          <Card>
            <CardHeader>
              <CardTitle>⚡ Lightning Fast</CardTitle>
              <CardDescription>
                Bun's JavaScriptCore engine provides exceptional performance
              </CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">
                Startup times up to 4x faster than Node.js with native ES modules support
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>📦 Built-in Bundler</CardTitle>
              <CardDescription>
                No separate bundler needed - Bun handles it all
              </CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">
                Fast bundling with tree-shaking, minification, and source maps
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>🔷 Native TypeScript</CardTitle>
              <CardDescription>
                TypeScript support without additional configuration
              </CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">
                Run TypeScript files directly with automatic compilation
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>🎯 Node.js Compatible</CardTitle>
              <CardDescription>
                Drop-in replacement with 90% npm package compatibility
              </CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">
                Most existing Node.js code runs without modifications
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>🛠️ Batteries Included</CardTitle>
              <CardDescription>
                Built-in tools for development and testing
              </CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">
                Package manager, test runner, and bundler all in one
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>🎨 Modern React</CardTitle>
              <CardDescription>
                React 18 with concurrent features and modern patterns
              </CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">
                Latest React features with fast refresh and optimized rendering
              </p>
            </CardContent>
          </Card>
        </div>

        {/* Interactive Demos */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-8">
          <Counter />
          <ApiDemo />
        </div>

        <div className="mb-8">
          <FileDemo />
        </div>

        {/* System Information */}
        <Card>
          <CardHeader>
            <CardTitle>💻 Runtime Information</CardTitle>
            <CardDescription>
              System and runtime details
            </CardDescription>
          </CardHeader>
          <CardContent>
            {isLoading ? (
              <div className="text-center py-4">
                <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto mb-4"></div>
                <p className="text-muted-foreground">Loading system information...</p>
              </div>
            ) : systemInfo ? (
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                <div className="bg-gray-50 dark:bg-gray-700 rounded-lg p-4">
                  <div className="text-sm font-medium text-gray-600 dark:text-gray-400 mb-1">Runtime</div>
                  <div className="text-lg font-semibold">{systemInfo.runtime}</div>
                </div>
                <div className="bg-gray-50 dark:bg-gray-700 rounded-lg p-4">
                  <div className="text-sm font-medium text-gray-600 dark:text-gray-400 mb-1">Version</div>
                  <div className="text-lg font-semibold">{systemInfo.version}</div>
                </div>
                <div className="bg-gray-50 dark:bg-gray-700 rounded-lg p-4">
                  <div className="text-sm font-medium text-gray-600 dark:text-gray-400 mb-1">Platform</div>
                  <div className="text-lg font-semibold">{systemInfo.platform}</div>
                </div>
                <div className="bg-gray-50 dark:bg-gray-700 rounded-lg p-4">
                  <div className="text-sm font-medium text-gray-600 dark:text-gray-400 mb-1">Timestamp</div>
                  <div className="text-sm font-semibold">{new Date(systemInfo.timestamp).toLocaleString()}</div>
                </div>
              </div>
            ) : (
              <p className="text-muted-foreground">Unable to load system information</p>
            )}
          </CardContent>
        </Card>

        {/* Getting Started */}
        <Card className="mt-8">
          <CardHeader>
            <CardTitle>🚀 Getting Started</CardTitle>
            <CardDescription>
              Quick setup instructions for the Bun template
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <div>
                <h3 className="text-xl font-semibold mb-4">Installation</h3>
                <div className="bg-gray-50 dark:bg-gray-700 rounded-lg p-4 font-mono text-sm">
                  <div className="mb-2"># Copy this template</div>
                  <div className="mb-2">cp -r bun-react-ts my-bun-app</div>
                  <div className="mb-2">cd my-bun-app</div>
                  <div className="mb-2"># Install dependencies</div>
                  <div>bun install</div>
                </div>
              </div>
              <div>
                <h3 className="text-xl font-semibold mb-4">Development</h3>
                <div className="bg-gray-50 dark:bg-gray-700 rounded-lg p-4 font-mono text-sm">
                  <div className="mb-2"># Start development server</div>
                  <div className="mb-2">bun run dev</div>
                  <div className="mb-2"># Build for production</div>
                  <div className="mb-2">bun run build</div>
                  <div className="mb-2"># Run tests</div>
                  <div>bun test</div>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </main>

      {/* Footer */}
      <footer className="border-t bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 mt-12">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <div className="text-center text-gray-600 dark:text-gray-400">
            <p>Built with Bun runtime, React, TypeScript, and Tailwind CSS</p>
            <p className="mt-2">Experience the future of JavaScript development</p>
          </div>
        </div>
      </footer>
    </div>
  );
}

export default App;
